# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='location.proto',
  package='location',
  serialized_pb='\n\x0elocation.proto\x12\x08location\"\xab\x01\n\rPlaneLocation\x12\x16\n\x0e\x61lt_agl_meters\x18\x01 \x01(\x02\x12\x16\n\x0e\x61lt_asl_meters\x18\x02 \x01(\x02\x12\x14\n\x0croll_degrees\x18\x03 \x01(\x02\x12\x15\n\rpitch_degrees\x18\x04 \x01(\x02\x12\x13\n\x0byaw_degrees\x18\x05 \x01(\x02\x12\x13\n\x0blat_degrees\x18\x06 \x01(\x01\x12\x13\n\x0blon_degrees\x18\x07 \x01(\x01')




_PLANELOCATION = _descriptor.Descriptor(
  name='PlaneLocation',
  full_name='location.PlaneLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alt_agl_meters', full_name='location.PlaneLocation.alt_agl_meters', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alt_asl_meters', full_name='location.PlaneLocation.alt_asl_meters', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roll_degrees', full_name='location.PlaneLocation.roll_degrees', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch_degrees', full_name='location.PlaneLocation.pitch_degrees', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw_degrees', full_name='location.PlaneLocation.yaw_degrees', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat_degrees', full_name='location.PlaneLocation.lat_degrees', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon_degrees', full_name='location.PlaneLocation.lon_degrees', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=200,
)

DESCRIPTOR.message_types_by_name['PlaneLocation'] = _PLANELOCATION

class PlaneLocation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLANELOCATION

  # @@protoc_insertion_point(class_scope:location.PlaneLocation)


# @@protoc_insertion_point(module_scope)
